# Odometry
- 
  ros_topic_name: "/X3/odom"
  gz_topic_name: "/X3/odometry"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "gz.msgs.Odometry"
  direction: BIDIRECTIONAL

# IMU
- 
  ros_topic_name: "/X3/imu"
  gz_topic_name: "/X3/imu"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "gz.msgs.IMU"
  direction: BIDIRECTIONAL

# Command Velocity (from ROS to Gazebo)
- 
  ros_topic_name: "/X3/cmd_vel"
  gz_topic_name: "/X3/cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "gz.msgs.Twist"
  direction: ROS_TO_GZ

# Clock (for synchronization)
- 
  ros_topic_name: "/clock"
  gz_topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS

  # ros_gz_bridge.yaml
- ros_topic_name: "/X3/enable"
  gz_topic_name: "/X3/enable"
  ros_type_name: "std_msgs/msg/Bool"
  gz_type_name: "gz.msgs.Boolean"
  direction: BIDIRECTIONAL  # Allows both ROS->Gazebo and Gazebo->ROS