distributed_kf3d:
  ros__parameters:
    # Initial uncertainty parameters
    initialUncertaintyPosXY: 100.0
    initialUncertaintyPosZ: 10.0
    initialUncertaintyVelXY: 1.0
    initialUncertaintyVelZ: 0.5
    initialUncertaintyOffsetXY: 1.0
    initialUncertaintyOffsetZ: 3.0
    
    # Process noise parameters
    noisePosXVar: 0.0
    noisePosYVar: 0.0
    noisePosZVar: 0.0
    noiseVelXVar: 0.5
    noiseVelYVar: 0.5
    noiseVelZVar: 0.1
    noiseOffXVar: 0.02
    noiseOffYVar: 0.02
    noiseOffZVar: 0.02
    
    # Global offset bias
    posGlobalOffsetBiasX: 0.0
    posGlobalOffsetBiasY: 0.0
    posGlobalOffsetBiasZ: 0.0
    
    # Decay times
    velocityDecayTime: 6.0
    offsetDecayTime: 30.0
    
    # False positive threshold
    falsePositiveThresholdSigma: 2.0
    
    # Time threshold for filter reset
    reset_time_threshold: 10.0
    
    # Cache configuration
    cache_size: 40
    
    # Publishing topics
    pub_topic: "target_tracker/pose"
    velPub_topic: "target_tracker/twist"
    offset_topic: "target_tracker/offset"